name: Global Scanner

on:
  pull_request:
    branches:
      - '**'

jobs:
  scan:
    uses: gks-composite/.github/.github/workflows/Global-Scan.yml@main
    secrets: inherit
    # with:
    #   image: ghcr.io/${{ github.repository_owner }}/your-image:latest
