name: Global Lint (on pull request)

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true # This updates PRs so it should be canceled if another run kicks off
  
jobs:
  lint:
    uses: gks-composite/.github/.github/workflows/Global-Lint.yml@main
    secrets: inherit
    with:
      branch: ${{ github.event.pull_request.base.ref || github.base_ref || github.ref_name || 'main' }}

