name: Version Manager (with override)

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true # Because the version can be branch bound, cancel existing runs on the ref
  
jobs:
  lint:
    if: ${{ github.event_name == 'pull_request' }}
    uses: gks-composite/.github/.github/workflows/Global-Lint.yml@main
    secrets: inherit
    with:
      branch: ${{ github.event.pull_request.base.ref || github.base_ref || github.ref_name || 'main' }}

