name: Generic Global Scanner

on:
  workflow_call:
    inputs:
      working_dir:
        description: 'directory should be scanned'
        required: false
        type: string
        default: "."
    secrets:
      OVERRIDE_TOKEN:
        required: false
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      statuses: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.OVERRIDE_TOKEN || secrets.GITHUB_TOKEN }}
          submodules: recursive
          persist-credentials: false

      - name: Run Trivy Scan
        uses: gks-composite/trivy-scan@v1
        with:
          scan-type: fs
          working-dir: ${{ inputs.working_dir }}
          severity: "HIGH,CRITICAL"
          exit-code: "0"
